# Reference URL: https://docs.docker.com/compose
version: '3.9'

services:
  appy_app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - APP_PORT=${APP_PORT}
    restart: unless-stopped
    stop_grace_period: 1s
    env_file:
      - ./.env.docker
    ports:
      - "${APP_PORT}:${APP_PORT}"
