name: Lint workflow
on: [push, pull_request]
jobs:
  lint:
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 42
      fail-fast: false
      matrix:
        os: [ubuntu-20.04, macos-latest, windows-latest]
        python-version: [3.6, 3.7, 3.9]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
            python-version: ${{ matrix.python-version }}
            cache: "pip"
      - name: "Install and run pre-commit via tox"
        run: |
              python -m pip install tox tox-gh-actions
              python -m tox -vv
